CREATE TABLE ADHERENTS (
  ID           NUMBER PRIMARY KEY,
  NOM          VARCHAR2(30),
  PRENOM       VARCHAR2(20),
  DATE_NAISS   DATE,
  TEL_ADH      VARCHAR2(20),
  ADRESSE_ADH  VARCHAR2(100),
  EMAIL        VARCHAR2(100)
);

CREATE TABLE EMPLOYES (
  ID     NUMBER PRIMARY KEY,
  NOM    VARCHAR2(30),
  PRENOM VARCHAR2(20),
  EMAIL  VARCHAR2(100),
  TEL    VARCHAR2(20),
  POSTE  VARCHAR2(60)
);

CREATE TABLE FORMATEURS (
  ID         NUMBER PRIMARY KEY,
  NOM        VARCHAR2(30),
  PRENOM     VARCHAR2(20),
  EMAIL      VARCHAR2(100),
  TEL        VARCHAR2(20),
  SPECIALITE VARCHAR2(100)
);

CREATE TABLE EQUIPEMENTS (
  REF       NUMBER PRIMARY KEY,
  NOM       VARCHAR2(60),
  QUANTITE  NUMBER,
  CATEGORIE VARCHAR2(60),
  PRIX      NUMBER
);

CREATE TABLE ATELIERS (
  REF          NUMBER PRIMARY KEY,
  NOM          VARCHAR2(60),
  CAPACITE     NUMBER,
  JOUR         VARCHAR2(10),
  HORAIRE      VARCHAR2(20),
  DUREE_MIN    NUMBER,
  N_SALLE      VARCHAR2(20),
  ID_ADHERENT  NUMBER,
  ID_EMPLOYE   NUMBER,
  CONSTRAINT FK_AT_ADH FOREIGN KEY (ID_ADHERENT) REFERENCES ADHERENTS(ID),
  CONSTRAINT FK_AT_EMP FOREIGN KEY (ID_EMPLOYE)  REFERENCES EMPLOYES(ID)
);

CREATE TABLE SUPPERVISER (
  ID_FORMATEUR NUMBER,
  REF_ATELIER  NUMBER,
  CONSTRAINT PK_SUPPERVISER PRIMARY KEY (ID_FORMATEUR, REF_ATELIER),
  CONSTRAINT FK_SUPP_IDF  FOREIGN KEY (ID_FORMATEUR) REFERENCES FORMATEURS(ID),
  CONSTRAINT FK_SUPP_REFA FOREIGN KEY (REF_ATELIER)  REFERENCES ATELIERS(REF)
);

CREATE TABLE NECESSITER (
  REF_ATELIER    NUMBER,
  REF_EQUIPEMENT NUMBER,
  CONSTRAINT PK_NECESSITER PRIMARY KEY (REF_ATELIER, REF_EQUIPEMENT),
  CONSTRAINT FK_NEC_REFA FOREIGN KEY (REF_ATELIER)    REFERENCES ATELIERS(REF),
  CONSTRAINT FK_NEC_REFE FOREIGN KEY (REF_EQUIPEMENT) REFERENCES EQUIPEMENTS(REF)
);
